# Generated by Django 4.2.1 on 2023-07-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hemoscuser',
            name='location',
            field=models.CharField(choices=[('FLORIANÓPOLIS', 'Florianópolis'), ('JOINVILLE', 'Joinville'), ('BLUMENAU', 'Blumenau'), ('CRICIÚMA', 'Criciúma'), ('LAGES', 'Lages'), ('JOAÇABA', 'Joaçaba'), ('CHAPECÓ', 'Chapecó')], max_length=20),
        ),
    ]
