# Generated by Django 4.1.7 on 2023-06-27 16:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hemocentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('ideal_qnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BloodBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], default='', max_length=3)),
                ('level', models.CharField(choices=[('CRITICO', 'Crítico'), ('BAIXO', 'Baixo'), ('ESTAVEL', 'Estável'), ('ADEQUADO', 'Adequado')], default='', max_length=10)),
                ('ideal_qnt', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bolsas.hemocentro')),
            ],
        ),
    ]
