# Generated by Django 4.2.1 on 2023-07-14 16:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hemocentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(choices=[('FLORIANÓPOLIS', 'Florianópolis'), ('JOINVILLE', 'Joinville'), ('BLUMENAU', 'Blumenau'), ('CRICIÚMA', 'Criciúma'), ('LAGES', 'Lages'), ('JOAÇABA', 'Joaçaba'), ('CHAPECÓ', 'Chapecó')], max_length=20)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='BloodBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], max_length=3)),
                ('level', models.CharField(choices=[('CRITICO', 'Crítico'), ('BAIXO', 'Baixo'), ('ESTAVEL', 'Estável'), ('ADEQUADO', 'Adequado')], max_length=10)),
                ('ideal_qnt', models.IntegerField()),
                ('total', models.IntegerField()),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bolsas.hemocentro')),
            ],
        ),
    ]
