# Generated by Django 4.2.1 on 2023-07-03 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsas', '0002_alter_bloodbag_level_alter_bloodbag_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodbag',
            old_name='quantity',
            new_name='total',
        ),
    ]
