# Generated by Django 4.2.1 on 2023-07-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsas', '0004_remove_hemocentro_ideal_qnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hemocentro',
            name='address',
            field=models.CharField(choices=[('FLORIANOPOLIS', 'Florianópolis'), ('JOINVILLE', 'Joinville'), ('BLUMENAU', 'Blumenau'), ('CRICIUMA', 'Criciúma'), ('LAGES', 'Lages'), ('JOACABA', 'Joaçaba'), ('CHAPECO', 'Chapecó')], max_length=20),
        ),
    ]
